spring:
  application:
    name: apigateway-server
  output:
    ansi:
      enabled: always
      
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

token:
  expiration_time: 86400000
  secret: abcdefghijklmnopqrstuvwxyz01234567890